-- 二手书交易平台种子数据：仅含 Open Library 有真封面的书籍（默认最多 25 本），无 picsum / 无 SVG 占位。
-- Generated by scripts/generate_seed.py
-- Books: 25, Wanted rows: (见下方 INSERT 或注释)
SET NAMES utf8mb4;

START TRANSACTION;

INSERT INTO `book` (`title`, `author`, `isbn`, `category_id`, `cover_image`, `description`, `price`, `original_price`, `condition`, `stock`, `seller_id`, `status`, `view_count`, `deleted`) VALUES
('百年孤独', '加西亚·马尔克斯', '9787544253994', 2, 'https://covers.openlibrary.org/b/isbn/9787544253994-M.jpg', '[SEED]《百年孤独》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #1）', 18.11, 61.29, 2, 1, 6, 1, 347, 0),
('围城', '钱锺书', '9787020024759', 2, 'https://covers.openlibrary.org/b/isbn/9787020024759-M.jpg', '[SEED]《围城》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #2）', 46.76, 148.74, 3, 1, 4, 1, 99, 0),
('红楼梦', '曹雪芹', '9787020002207', 2, 'https://covers.openlibrary.org/b/isbn/9787020002207-M.jpg', '[SEED]《红楼梦》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #3）', 10.17, 27.15, 3, 1, 3, 1, 374, 0),
('三体', '刘慈欣', '9787536692930', 2, 'https://covers.openlibrary.org/b/isbn/9787536692930-M.jpg', '[SEED]《三体》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #4）', 47.67, 132.58, 3, 1, 5, 1, 220, 0),
('三体Ⅱ·黑暗森林', '刘慈欣', '9787536693968', 2, 'https://covers.openlibrary.org/b/isbn/9787536693968-M.jpg', '[SEED]《三体Ⅱ·黑暗森林》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #5）', 18.03, 51.58, 2, 1, 5, 1, 276, 0),
('挪威的森林', '村上春树', '9787532725694', 2, 'https://covers.openlibrary.org/b/isbn/9787532725694-M.jpg', '[SEED]《挪威的森林》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #6）', 15.14, 51.96, 3, 1, 6, 1, 38, 0),
('追风筝的人', '卡勒德·胡赛尼', '9787208061644', 2, 'https://covers.openlibrary.org/b/isbn/9787208061644-M.jpg', '[SEED]《追风筝的人》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #7）', 28.78, 43.93, 3, 1, 2, 1, 135, 0),
('灿烂千阳', '卡勒德·胡赛尼', '9787208072107', 2, 'https://covers.openlibrary.org/b/isbn/9787208072107-M.jpg', '[SEED]《灿烂千阳》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #8）', 17.59, 55.06, 3, 1, 3, 1, 263, 0),
('解忧杂货店', '东野圭吾', '9787544270878', 2, 'https://covers.openlibrary.org/b/isbn/9787544270878-M.jpg', '[SEED]《解忧杂货店》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #9）', 30.82, 69.3, 2, 1, 6, 1, 105, 0),
('白夜行', '东野圭吾', '9787544242516', 2, 'https://covers.openlibrary.org/b/isbn/9787544242516-M.jpg', '[SEED]《白夜行》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #10）', 25.98, 74.8, 2, 1, 5, 1, 161, 0),
('悟空传', '今何在', '9787544251785', 2, 'https://covers.openlibrary.org/b/isbn/9787544251785-M.jpg', '[SEED]《悟空传》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #11）', 52.24, 158.44, 4, 1, 6, 1, 343, 0),
('万历十五年', '黄仁宇', '9787108009821', 11, 'https://covers.openlibrary.org/b/isbn/9787108009821-M.jpg', '[SEED]《万历十五年》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #12）', 29.31, 58.26, 1, 1, 2, 1, 109, 0),
('未来简史', '尤瓦尔·赫拉利', '9787508672069', 11, 'https://covers.openlibrary.org/b/isbn/9787508672069-M.jpg', '[SEED]《未来简史》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #13）', 44.22, 71.77, 3, 1, 2, 1, 141, 0),
('中国大历史', '黄仁宇', '9787108010360', 11, 'https://covers.openlibrary.org/b/isbn/9787108010360-M.jpg', '[SEED]《中国大历史》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #14）', 39.26, 83.68, 4, 1, 3, 2, 369, 0),
('史记', '司马迁', '9787101003086', 11, 'https://covers.openlibrary.org/b/isbn/9787101003086-M.jpg', '[SEED]《史记》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #15）', 45.09, 81.69, 2, 1, 3, 1, 39, 0),
('资治通鉴', '司马光', '9787101003093', 11, 'https://covers.openlibrary.org/b/isbn/9787101003093-M.jpg', '[SEED]《资治通鉴》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #16）', 15.38, 49.86, 2, 1, 5, 1, 352, 0),
('时间简史', '斯蒂芬·霍金', '9787535732309', 12, 'https://covers.openlibrary.org/b/isbn/9787535732309-M.jpg', '[SEED]《时间简史》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #17）', 43.37, 114.38, 2, 1, 4, 0, 391, 0),
('经济学原理：微观经济学', '曼昆', '9787301150894', 1, 'https://covers.openlibrary.org/b/isbn/9787301150894-M.jpg', '[SEED]《经济学原理：微观经济学》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #18）', 32.89, 78.72, 1, 1, 2, 0, 219, 0),
('穷查理宝典', '查理·芒格', '9787508661902', 1, 'https://covers.openlibrary.org/b/isbn/9787508661902-M.jpg', '[SEED]《穷查理宝典》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #19）', 44.77, 135.29, 3, 1, 4, 0, 386, 0),
('巴菲特致股东的信', '沃伦·巴菲特', '9787111407010', 1, 'https://covers.openlibrary.org/b/isbn/9787111407010-M.jpg', '[SEED]《巴菲特致股东的信》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #20）', 27.05, 41.64, 3, 2, 2, 1, 166, 0),
('创新者的窘境', '克莱顿·克里斯坦森', '9787508633558', 1, 'https://covers.openlibrary.org/b/isbn/9787508633558-M.jpg', '[SEED]《创新者的窘境》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #21）', 38.23, 123.31, 4, 1, 4, 1, 75, 0),
('深入理解计算机系统', '兰德尔·布莱恩特', '9787111544937', 4, 'https://covers.openlibrary.org/b/isbn/9787111544937-M.jpg', '[SEED]《深入理解计算机系统》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #22）', 41.76, 137.95, 1, 2, 2, 1, 396, 0),
('Clean Code', '罗伯特·马丁', '9780132350884', 4, 'https://covers.openlibrary.org/b/isbn/9780132350884-M.jpg', '[SEED]《Clean Code》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #23）', 11.66, 35.85, 3, 1, 3, 1, 8, 0),
('计算机程序设计艺术', '高德纳', '9780201485417', 4, 'https://covers.openlibrary.org/b/isbn/9780201485417-M.jpg', '[SEED]《计算机程序设计艺术》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #24）', 37.45, 68.85, 1, 1, 6, 1, 121, 0),
('编译原理', '阿尔弗雷德·阿霍', '9787111251217', 4, 'https://covers.openlibrary.org/b/isbn/9787111251217-M.jpg', '[SEED]《编译原理》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #25）', 27.62, 48.01, 1, 1, 5, 1, 258, 0);

INSERT INTO `book_wanted` (`user_id`, `book_title`, `author`, `isbn`, `cover_image`, `description`, `max_price`, `status`, `view_count`, `deleted`) VALUES
(5, '求购《红楼梦》脂评本', '曹雪芹', '9787020002207', 'https://covers.openlibrary.org/b/isbn/9787020002207-M.jpg', '[SEED]想找一套脂砚斋评点本，品相不限，价格合理即可。（种子批次 #1）', 26.58, 1, 136, 0),
(5, '求购《百年孤独》首版中译本', '加西亚·马尔克斯', '9787544253994', 'https://covers.openlibrary.org/b/isbn/9787544253994-M.jpg', '[SEED]收藏用，希望书况较好，有护封更好。（种子批次 #2）', 22.85, 1, 325, 0),
(5, '求购《三体》签名本', '刘慈欣', '9787536692930', 'https://covers.openlibrary.org/b/isbn/9787536692930-M.jpg', '[SEED]刘慈欣签名本优先，普通版也可，要求正版。（种子批次 #3）', 44.48, 1, 258, 0),
(3, '求购《围城》老版本', '钱锺书', '9787020024759', 'https://covers.openlibrary.org/b/isbn/9787020024759-M.jpg', '[SEED]2000年以前的版本均可，品相无所谓。（种子批次 #4）', 9.16, 2, 336, 0),
(3, '求购金庸全集', '金庸', '9787108009821', 'https://covers.openlibrary.org/b/isbn/9787108009821-M.jpg', '[SEED]希望收一套较完整的金庸武侠小说全集。（种子批次 #5）', 41.49, 1, 53, 0),
(6, '求购《时间简史》插图版', '霍金', '9787535732309', 'https://covers.openlibrary.org/b/isbn/9787535732309-M.jpg', '[SEED]插图版优先，普通版也考虑。（种子批次 #6）', 8.06, 1, 179, 0),
(3, '求购《万历十五年》', '黄仁宇', '9787108009821', 'https://covers.openlibrary.org/b/isbn/9787108009821-M.jpg', '[SEED]经典版本即可，内容完整无缺页。（种子批次 #7）', 34.88, 1, 146, 0),
(3, '求购《白夜行》', '东野圭吾', '9787544242516', 'https://covers.openlibrary.org/b/isbn/9787544242516-M.jpg', '[SEED]东野圭吾的书都收，优先白夜行。（种子批次 #8）', 49.79, 1, 28, 0),
(5, '求购《解忧杂货店》', '东野圭吾', '9787544270878', 'https://covers.openlibrary.org/b/isbn/9787544270878-M.jpg', '[SEED]品相好一些的优先。（种子批次 #9）', 23.24, 2, 237, 0),
(4, '求购《挪威的森林》日文原版', '村上春树', '9787532725694', 'https://covers.openlibrary.org/b/isbn/9787532725694-M.jpg', '[SEED]日文原版优先，中文版也可。（种子批次 #10）', 22.15, 1, 137, 0),
(6, '求购《追风筝的人》', '卡勒德·胡赛尼', '9787208061644', 'https://covers.openlibrary.org/b/isbn/9787208061644-M.jpg', '[SEED]品相好的优先。（种子批次 #11）', 31.18, 1, 123, 0),
(6, '求购数据结构和算法教材', '不限', '9787111407010', 'https://covers.openlibrary.org/b/isbn/9787111407010-M.jpg', '[SEED]适合自学，用Python或Java讲解均可。（种子批次 #12）', 57.28, 1, 149, 0);

-- 30 条模拟订单（通过 ISBN 子查询关联书籍）
INSERT INTO `order` (`order_no`, `buyer_id`, `seller_id`, `book_id`, `quantity`, `total_price`, `status`, `payment_time`, `delivery_time`, `finish_time`, `remark`, `create_time`, `update_time`, `deleted`) VALUES
('SEED5523000', 5, (SELECT seller_id FROM book WHERE isbn='9787208072107' AND deleted=0 LIMIT 1), (SELECT book_id FROM book WHERE isbn='9787208072107' AND deleted=0 LIMIT 1), 1, (SELECT COALESCE(price, 0) FROM book WHERE isbn='9787208072107' AND deleted=0 LIMIT 1), 5, NOW(), NOW(), NOW(), '种子订单 #1', NOW(), NOW(), 0),
('SEED9751001', 6, (SELECT seller_id FROM book WHERE isbn='9787508633558' AND deleted=0 LIMIT 1), (SELECT book_id FROM book WHERE isbn='9787508633558' AND deleted=0 LIMIT 1), 1, (SELECT COALESCE(price, 0) FROM book WHERE isbn='9787508633558' AND deleted=0 LIMIT 1), 4, NOW(), NOW(), NOW(), '种子订单 #2', NOW(), NOW(), 0),
('SEED7917002', 3, (SELECT seller_id FROM book WHERE isbn='9787111544937' AND deleted=0 LIMIT 1), (SELECT book_id FROM book WHERE isbn='9787111544937' AND deleted=0 LIMIT 1), 1, (SELECT COALESCE(price, 0) FROM book WHERE isbn='9787111544937' AND deleted=0 LIMIT 1), 3, NOW(), NOW(), NULL, '种子订单 #3', NOW(), NOW(), 0),
('SEED1903003', 3, (SELECT seller_id FROM book WHERE isbn='9787532725694' AND deleted=0 LIMIT 1), (SELECT book_id FROM book WHERE isbn='9787532725694' AND deleted=0 LIMIT 1), 1, (SELECT COALESCE(price, 0) FROM book WHERE isbn='9787532725694' AND deleted=0 LIMIT 1), 1, NULL, NULL, NULL, '种子订单 #4', NOW(), NOW(), 0),
('SEED2952004', 5, (SELECT seller_id FROM book WHERE isbn='9787535732309' AND deleted=0 LIMIT 1), (SELECT book_id FROM book WHERE isbn='9787535732309' AND deleted=0 LIMIT 1), 1, (SELECT COALESCE(price, 0) FROM book WHERE isbn='9787535732309' AND deleted=0 LIMIT 1), 4, NOW(), NOW(), NOW(), '种子订单 #5', NOW(), NOW(), 0),
('SEED3026005', 2, (SELECT seller_id FROM book WHERE isbn='9787101003086' AND deleted=0 LIMIT 1), (SELECT book_id FROM book WHERE isbn='9787101003086' AND deleted=0 LIMIT 1), 1, (SELECT COALESCE(price, 0) FROM book WHERE isbn='9787101003086' AND deleted=0 LIMIT 1), 2, NOW(), NULL, NULL, '种子订单 #6', NOW(), NOW(), 0),
('SEED3915006', 3, (SELECT seller_id FROM book WHERE isbn='9787208061644' AND deleted=0 LIMIT 1), (SELECT book_id FROM book WHERE isbn='9787208061644' AND deleted=0 LIMIT 1), 1, (SELECT COALESCE(price, 0) FROM book WHERE isbn='9787208061644' AND deleted=0 LIMIT 1), 4, NOW(), NOW(), NOW(), '种子订单 #7', NOW(), NOW(), 0),
('SEED5901007', 6, (SELECT seller_id FROM book WHERE isbn='9787108010360' AND deleted=0 LIMIT 1), (SELECT book_id FROM book WHERE isbn='9787108010360' AND deleted=0 LIMIT 1), 1, (SELECT COALESCE(price, 0) FROM book WHERE isbn='9787108010360' AND deleted=0 LIMIT 1), 5, NOW(), NOW(), NOW(), '种子订单 #8', NOW(), NOW(), 0),
('SEED5661008', 5, (SELECT seller_id FROM book WHERE isbn='9787536692930' AND deleted=0 LIMIT 1), (SELECT book_id FROM book WHERE isbn='9787536692930' AND deleted=0 LIMIT 1), 1, (SELECT COALESCE(price, 0) FROM book WHERE isbn='9787536692930' AND deleted=0 LIMIT 1), 4, NOW(), NOW(), NOW(), '种子订单 #9', NOW(), NOW(), 0),
('SEED9282009', 3, (SELECT seller_id FROM book WHERE isbn='9787544253994' AND deleted=0 LIMIT 1), (SELECT book_id FROM book WHERE isbn='9787544253994' AND deleted=0 LIMIT 1), 1, (SELECT COALESCE(price, 0) FROM book WHERE isbn='9787544253994' AND deleted=0 LIMIT 1), 2, NOW(), NULL, NULL, '种子订单 #10', NOW(), NOW(), 0),
('SEED9246010', 4, (SELECT seller_id FROM book WHERE isbn='9787536693968' AND deleted=0 LIMIT 1), (SELECT book_id FROM book WHERE isbn='9787536693968' AND deleted=0 LIMIT 1), 1, (SELECT COALESCE(price, 0) FROM book WHERE isbn='9787536693968' AND deleted=0 LIMIT 1), 3, NOW(), NOW(), NULL, '种子订单 #11', NOW(), NOW(), 0),
('SEED9515011', 3, (SELECT seller_id FROM book WHERE isbn='9787544251785' AND deleted=0 LIMIT 1), (SELECT book_id FROM book WHERE isbn='9787544251785' AND deleted=0 LIMIT 1), 1, (SELECT COALESCE(price, 0) FROM book WHERE isbn='9787544251785' AND deleted=0 LIMIT 1), 4, NOW(), NOW(), NOW(), '种子订单 #12', NOW(), NOW(), 0),
('SEED9454012', 2, (SELECT seller_id FROM book WHERE isbn='9787301150894' AND deleted=0 LIMIT 1), (SELECT book_id FROM book WHERE isbn='9787301150894' AND deleted=0 LIMIT 1), 1, (SELECT COALESCE(price, 0) FROM book WHERE isbn='9787301150894' AND deleted=0 LIMIT 1), 3, NOW(), NOW(), NULL, '种子订单 #13', NOW(), NOW(), 0),
('SEED5563013', 5, (SELECT seller_id FROM book WHERE isbn='9787508661902' AND deleted=0 LIMIT 1), (SELECT book_id FROM book WHERE isbn='9787508661902' AND deleted=0 LIMIT 1), 1, (SELECT COALESCE(price, 0) FROM book WHERE isbn='9787508661902' AND deleted=0 LIMIT 1), 4, NOW(), NOW(), NOW(), '种子订单 #14', NOW(), NOW(), 0),
('SEED2162014', 5, (SELECT seller_id FROM book WHERE isbn='9780201485417' AND deleted=0 LIMIT 1), (SELECT book_id FROM book WHERE isbn='9780201485417' AND deleted=0 LIMIT 1), 1, (SELECT COALESCE(price, 0) FROM book WHERE isbn='9780201485417' AND deleted=0 LIMIT 1), 2, NOW(), NULL, NULL, '种子订单 #15', NOW(), NOW(), 0),
('SEED6168015', 5, (SELECT seller_id FROM book WHERE isbn='9787544270878' AND deleted=0 LIMIT 1), (SELECT book_id FROM book WHERE isbn='9787544270878' AND deleted=0 LIMIT 1), 1, (SELECT COALESCE(price, 0) FROM book WHERE isbn='9787544270878' AND deleted=0 LIMIT 1), 3, NOW(), NOW(), NULL, '种子订单 #16', NOW(), NOW(), 0),
('SEED8352016', 2, (SELECT seller_id FROM book WHERE isbn='9787020024759' AND deleted=0 LIMIT 1), (SELECT book_id FROM book WHERE isbn='9787020024759' AND deleted=0 LIMIT 1), 1, (SELECT COALESCE(price, 0) FROM book WHERE isbn='9787020024759' AND deleted=0 LIMIT 1), 4, NOW(), NOW(), NOW(), '种子订单 #17', NOW(), NOW(), 0),
('SEED4664017', 6, (SELECT seller_id FROM book WHERE isbn='9780132350884' AND deleted=0 LIMIT 1), (SELECT book_id FROM book WHERE isbn='9780132350884' AND deleted=0 LIMIT 1), 1, (SELECT COALESCE(price, 0) FROM book WHERE isbn='9780132350884' AND deleted=0 LIMIT 1), 1, NULL, NULL, NULL, '种子订单 #18', NOW(), NOW(), 0),
('SEED5018018', 5, (SELECT seller_id FROM book WHERE isbn='9787101003093' AND deleted=0 LIMIT 1), (SELECT book_id FROM book WHERE isbn='9787101003093' AND deleted=0 LIMIT 1), 1, (SELECT COALESCE(price, 0) FROM book WHERE isbn='9787101003093' AND deleted=0 LIMIT 1), 1, NULL, NULL, NULL, '种子订单 #19', NOW(), NOW(), 0),
('SEED5629019', 2, (SELECT seller_id FROM book WHERE isbn='9787111407010' AND deleted=0 LIMIT 1), (SELECT book_id FROM book WHERE isbn='9787111407010' AND deleted=0 LIMIT 1), 1, (SELECT COALESCE(price, 0) FROM book WHERE isbn='9787111407010' AND deleted=0 LIMIT 1), 3, NOW(), NOW(), NULL, '种子订单 #20', NOW(), NOW(), 0),
('SEED1028020', 4, (SELECT seller_id FROM book WHERE isbn='9787108009821' AND deleted=0 LIMIT 1), (SELECT book_id FROM book WHERE isbn='9787108009821' AND deleted=0 LIMIT 1), 1, (SELECT COALESCE(price, 0) FROM book WHERE isbn='9787108009821' AND deleted=0 LIMIT 1), 5, NOW(), NOW(), NOW(), '种子订单 #21', NOW(), NOW(), 0),
('SEED6547021', 2, (SELECT seller_id FROM book WHERE isbn='9787508672069' AND deleted=0 LIMIT 1), (SELECT book_id FROM book WHERE isbn='9787508672069' AND deleted=0 LIMIT 1), 1, (SELECT COALESCE(price, 0) FROM book WHERE isbn='9787508672069' AND deleted=0 LIMIT 1), 5, NOW(), NOW(), NOW(), '种子订单 #22', NOW(), NOW(), 0),
('SEED8744022', 2, (SELECT seller_id FROM book WHERE isbn='9787111251217' AND deleted=0 LIMIT 1), (SELECT book_id FROM book WHERE isbn='9787111251217' AND deleted=0 LIMIT 1), 1, (SELECT COALESCE(price, 0) FROM book WHERE isbn='9787111251217' AND deleted=0 LIMIT 1), 4, NOW(), NOW(), NOW(), '种子订单 #23', NOW(), NOW(), 0),
('SEED3612023', 6, (SELECT seller_id FROM book WHERE isbn='9787544242516' AND deleted=0 LIMIT 1), (SELECT book_id FROM book WHERE isbn='9787544242516' AND deleted=0 LIMIT 1), 1, (SELECT COALESCE(price, 0) FROM book WHERE isbn='9787544242516' AND deleted=0 LIMIT 1), 4, NOW(), NOW(), NOW(), '种子订单 #24', NOW(), NOW(), 0),
('SEED8732024', 3, (SELECT seller_id FROM book WHERE isbn='9787020002207' AND deleted=0 LIMIT 1), (SELECT book_id FROM book WHERE isbn='9787020002207' AND deleted=0 LIMIT 1), 1, (SELECT COALESCE(price, 0) FROM book WHERE isbn='9787020002207' AND deleted=0 LIMIT 1), 4, NOW(), NOW(), NOW(), '种子订单 #25', NOW(), NOW(), 0);

COMMIT;

-- Total: 25 books + 12 wanted + 25 orders
