-- 二手书交易平台种子数据：封面来自 Google Books API（imageLinks，经 GET 校验或跳过校验）。
-- Generated by scripts/generate_seed_google.py
-- 使用须遵守 https://developers.google.com/books/terms
-- Books: 24, Wanted rows: (见下方)
SET NAMES utf8mb4;

START TRANSACTION;

INSERT INTO `book` (`title`, `author`, `isbn`, `category_id`, `cover_image`, `description`, `price`, `original_price`, `condition`, `stock`, `seller_id`, `status`, `view_count`, `deleted`) VALUES
('百年孤独', '加西亚·马尔克斯', '9787544253994', 2, 'https://books.google.com/books/content?id=NOLiuAEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]《百年孤独》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #1）', 54.81, 92.72, 3, 1, 4, 1, 372, 0),
('围城', '钱锺书', '9787020024759', 2, 'https://books.google.com/books/content?id=MdFRQgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]《围城》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #2）', 41.13, 61.37, 2, 1, 6, 1, 12, 0),
('三体Ⅱ·黑暗森林', '刘慈欣', '9787536693968', 2, 'https://books.google.com/books/content?id=5ZCgQwAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]《三体Ⅱ·黑暗森林》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #3）', 26.53, 79.35, 3, 1, 6, 1, 395, 0),
('追风筝的人', '卡勒德·胡赛尼', '9787208061644', 2, 'https://books.google.com/books/content?id=NoGJAwAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]《追风筝的人》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #4）', 22.78, 54.68, 3, 1, 2, 2, 315, 0),
('灿烂千阳', '卡勒德·胡赛尼', '9787208072107', 2, 'https://books.google.com/books/content?id=g-KsJwAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]《灿烂千阳》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #5）', 53.91, 99.11, 3, 2, 4, 1, 302, 0),
('解忧杂货店', '东野圭吾', '9787544270878', 2, 'https://books.google.com/books/content?id=ljHeoAEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]《解忧杂货店》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #6）', 31.2, 42.84, 3, 1, 6, 1, 121, 0),
('白夜行', '东野圭吾', '9787544242516', 2, 'https://books.google.com/books/content?id=bVgyiViWjJUC&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]《白夜行》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #7）', 7.28, 25.37, 4, 1, 6, 2, 359, 0),
('边城', '沈从文', '9787020022221', 2, 'https://books.google.com/books/content?id=Wkh2AAAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]《边城》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #8）', 13.62, 40.32, 3, 1, 4, 0, 172, 0),
('星际迷航：红衫', '约翰·斯卡尔齐', '9787536493751', 9, 'https://books.google.com/books/content?id=AIC7wgEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]《星际迷航：红衫》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #9）', 22.79, 73.46, 3, 1, 4, 1, 159, 0),
('万历十五年', '黄仁宇', '9787108009821', 11, 'https://books.google.com/books/content?id=xEIRAQAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]《万历十五年》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #10）', 24.97, 68.46, 4, 1, 3, 1, 37, 0),
('未来简史', '尤瓦尔·赫拉利', '9787508672069', 11, 'https://books.google.com/books/content?id=gsOPswEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]《未来简史》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #11）', 29.06, 44.08, 2, 1, 3, 1, 111, 0),
('中国大历史', '黄仁宇', '9787108010360', 11, 'https://books.google.com/books/content?id=Ot93AAAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]《中国大历史》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #12）', 18.43, 25.18, 3, 1, 6, 1, 49, 0),
('史记', '司马迁', '9787101003086', 11, 'https://books.google.com/books/content?id=J4EfAQAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]《史记》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #13）', 53.4, 97.59, 2, 1, 2, 1, 318, 0),
('时间简史', '斯蒂芬·霍金', '9787535732309', 12, 'https://books.google.com/books/content?id=K3R97EjAwu8C&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]《时间简史》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #14）', 16.95, 52.7, 4, 1, 5, 2, 180, 0),
('查拉图斯特拉如是说', '尼采', '9787100021241', 13, 'https://books.google.com/books/content?id=YEpLAAAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]《查拉图斯特拉如是说》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #15）', 5.07, 8.55, 2, 1, 4, 0, 124, 0),
('中国哲学简史', '冯友兰', '9787108009807', 13, 'https://books.google.com/books/content?id=gbIpAQAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]《中国哲学简史》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #16）', 29.57, 74.93, 2, 1, 6, 1, 300, 0),
('Clean Code', '罗伯特·马丁', '9780132350884', 4, 'https://books.google.com/books/content?id=hjEFCAAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]《Clean Code》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #17）', 21.98, 45.27, 2, 1, 2, 1, 332, 0),
('计算机程序设计艺术', '高德纳', '9780201485417', 4, 'https://books.google.com/books/content?id=Kp06uAAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]《计算机程序设计艺术》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #18）', 22.96, 32.54, 3, 1, 6, 2, 245, 0),
('Effective Java', '约书亚·布洛赫', '9780134685991', 4, 'https://books.google.com/books/content?id=1cVqswEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]《Effective Java》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #19）', 18.36, 32.49, 2, 3, 3, 2, 378, 0),
('美的历程', '李泽厚', '9787108009838', 7, 'https://books.google.com/books/content?id=Y7-EAAAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]《美的历程》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #20）', 54.09, 148.49, 3, 1, 6, 1, 245, 0),
('小王子', '圣埃克苏佩里', '9787020042494', 8, 'https://books.google.com/books/content?id=i3qmAAAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]《小王子》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #21）', 19.06, 51.57, 3, 3, 2, 1, 274, 0),
('我决定简单地生活', '佐佐木典士', '9787544248853', 8, 'https://books.google.com/books/content?id=Ea1cygAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]《我决定简单地生活》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #22）', 44.03, 95.37, 3, 1, 5, 1, 256, 0),
('联邦党人文集', '汉密尔顿', '9787100021302', 10, 'https://books.google.com/books/content?id=EspMAQAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]《联邦党人文集》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #23）', 9.18, 32.12, 3, 1, 5, 1, 93, 0),
('黄帝内经', '佚名', '9787101003062', 6, 'https://books.google.com/books/content?id=4s9nAAAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]《黄帝内经》— 一本值得反复阅读的好书。品相良好，内页干净无笔记。（种子批次 #24）', 51.98, 82.94, 3, 1, 4, 1, 237, 0);

INSERT INTO `book_wanted` (`user_id`, `book_title`, `author`, `isbn`, `cover_image`, `description`, `max_price`, `status`, `view_count`, `deleted`) VALUES
(5, '求购《百年孤独》首版中译本', '加西亚·马尔克斯', '9787544253994', 'https://books.google.com/books/content?id=NOLiuAEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]收藏用，希望书况较好，有护封更好。（种子批次 #1）', 38.41, 1, 202, 0),
(2, '求购《围城》老版本', '钱锺书', '9787020024759', 'https://books.google.com/books/content?id=MdFRQgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]2000年以前的版本均可，品相无所谓。（种子批次 #2）', 14.89, 1, 340, 0),
(3, '求购金庸全集', '金庸', '9787108009821', 'https://books.google.com/books/content?id=xEIRAQAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]希望收一套较完整的金庸武侠小说全集。（种子批次 #3）', 32.13, 1, 234, 0),
(4, '求购《时间简史》插图版', '霍金', '9787535732309', 'https://books.google.com/books/content?id=K3R97EjAwu8C&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]插图版优先，普通版也考虑。（种子批次 #4）', 24.19, 1, 204, 0),
(4, '求购《万历十五年》', '黄仁宇', '9787108009821', 'https://books.google.com/books/content?id=xEIRAQAAMAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]经典版本即可，内容完整无缺页。（种子批次 #5）', 41.24, 1, 291, 0),
(3, '求购《白夜行》', '东野圭吾', '9787544242516', 'https://books.google.com/books/content?id=bVgyiViWjJUC&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]东野圭吾的书都收，优先白夜行。（种子批次 #6）', 20.92, 1, 50, 0),
(3, '求购《解忧杂货店》', '东野圭吾', '9787544270878', 'https://books.google.com/books/content?id=ljHeoAEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]品相好一些的优先。（种子批次 #7）', 24.63, 1, 168, 0),
(6, '求购《追风筝的人》', '卡勒德·胡赛尼', '9787208061644', 'https://books.google.com/books/content?id=NoGJAwAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]品相好的优先。（种子批次 #8）', 14.81, 1, 346, 0),
(4, '求购《小王子》中法对照版', '圣埃克苏佩里', '9787020042494', 'https://books.google.com/books/content?id=i3qmAAAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]中法对照最佳，收藏用。（种子批次 #9）', 50.96, 1, 40, 0),
(2, '求购《边城》沈从文', '沈从文', '9787020022221', 'https://books.google.com/books/content?id=Wkh2AAAAIAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', '[SEED]老版本优先，品相不限。（种子批次 #10）', 8.57, 1, 131, 0);

COMMIT;

-- Total: 24 books + 10 wanted（无订单 INSERT）
